DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;


CREATE TABLE KUNDE (
    KUNDENNR        INTEGER NOT NULL,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM    DATE,
	STRASSE         VARCHAR(50),
	HAUSNR		    VARCHAR(6),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50),
    PLZ             VARCHAR(5)
    );

CREATE TABLE BESTELLUNG(
    BESTELLNR       INTEGER NOT NULL,
    KUNDENNR        INTEGER,
    DATUM           DATE,
    NETTOPREIS      DECIMAL(10,2)
);

CREATE TABLE ZUTAT (
    ZID             INTEGER NOT NULL,
    ZUTAT       VARCHAR(50),
    MENGENEINHEIT   VARCHAR(25),
    KALORIEN        INTEGER,
    BESTAND         INTEGER,
    NETTOPREIS      DECIMAL(10,2),
    FETT            DECIMAL(10,2),
    KOHLENHYDRATE   DECIMAL(10,2)
);

CREATE TABLE ALLERGENE (
    AID             VARCHAR(1),
    BESCHREIBUNG    VARCHAR(500),
    ALLERGEN     	VARCHAR(25)
);

CREATE TABLE EAKATEGORIENAME (
    EID             INTEGER NOT NULL,
    BESCHREIBUNG    VARCHAR(500),
    ENKATEGORIE		VARCHAR(25)
);

CREATE TABLE LIEFERANT (
    LIEFERANTENNR   INTEGER NOT NULL,
    STRASSE         VARCHAR(50),
    HAUSNR          VARCHAR(6),
    LIEFERANT       VARCHAR(25),
    PLZ             VARCHAR(5) 
);

CREATE TABLE ORT (
    PLZ             VARCHAR(5),
    STADT           VARCHAR(50)
);

CREATE TABLE REZEPTE (
    RID             INTEGER NOT NULL,
    REZEPTE         VARCHAR(25),
    BESCHREIBUNG    VARCHAR(500)  
);

CREATE TABLE BESTELLUNG_ZUTAT (
    BESTELLNR       INTEGER,
    ZID             INTEGER,
    MENGE           INTEGER
);

CREATE TABLE ZUTAT_ALLERGENE (
    AID             VARCHAR(1),
    ZID             INTEGER
);

CREATE TABLE ZUTAT_EKG (
    EID             INTEGER,
    ZID             INTEGER
);

CREATE TABLE REZEPT_ZUTAT (
    RID             INTEGER,
    ZID             INTEGER,
    MENGE           INTEGER
);

CREATE TABLE LIEFERANT_ZUTAT ( 
    LIEFERANTENNR       INTEGER,
    ZID                 INTEGER
);

/******************************************************************************/
/***                              Primary Keys                              ***/
/******************************************************************************/

ALTER TABLE KUNDE ADD PRIMARY KEY (KUNDENNR);
ALTER TABLE BESTELLUNG ADD PRIMARY KEY (BESTELLNR);
ALTER TABLE ZUTAT ADD PRIMARY KEY (ZID);
ALTER TABLE ALLERGENE ADD PRIMARY KEY (AID);
ALTER TABLE EAKATEGORIENAME ADD PRIMARY KEY (EID);
ALTER TABLE LIEFERANT ADD PRIMARY KEY (LIEFERANTENNR);
ALTER TABLE ORT ADD PRIMARY KEY (PLZ);

/* ZUSAMMENGESEZTE PRIMARY KEYS */

ALTER TABLE REZEPTE ADD PRIMARY KEY (RID);
ALTER TABLE BESTELLUNG_ZUTAT ADD PRIMARY KEY (BESTELLNR, ZID);
ALTER TABLE ZUTAT_ALLERGENE ADD PRIMARY KEY (AID,ZID);
ALTER TABLE ZUTAT_EKG ADD PRIMARY KEY (EID,ZID);
ALTER TABLE REZEPT_ZUTAT ADD PRIMARY KEY (RID, ZID);
ALTER TABLE LIEFERANT_ZUTAT ADD PRIMARY KEY (LIEFERANTENNR,ZID);



/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE KUNDE ADD FOREIGN KEY (PLZ) REFERENCES ORT (PLZ);
ALTER TABLE LIEFERANT ADD FOREIGN KEY (PLZ) REFERENCES ORT (PLZ);