DROP DATABASE IF EXISTS krautundrueben;
CREATE DATABASE IF NOT EXISTS krautundrueben;
USE krautundrueben;


CREATE TABLE KUNDE (
    KUNDENNR        INTEGER AUTO_INCREMENT NOT NULL,
    NACHNAME        VARCHAR(50),
    VORNAME         VARCHAR(50),
    GEBURTSDATUM    DATE,
	STRASSE         VARCHAR(50),
	HAUSNR		    VARCHAR(6),
    TELEFON         VARCHAR(25),
    EMAIL           VARCHAR(50),
    PLZ             VARCHAR(5),
    PRIMARY KEY (KUNDENNR)
    );

CREATE TABLE BESTELLUNG(
    BESTELLNR       INTEGER AUTO_INCREMENT  NOT NULL,
    KUNDENNR        INTEGER,
    BESTELLDATUM    DATE,
    RECHNUNGSBETRAG DECIMAL(10,2),
    PRIMARY KEY (BESTELLNR)
);

CREATE TABLE ZUTATEN (
    ZID             INTEGER AUTO_INCREMENT NOT NULL,
    ZUTAT           VARCHAR(50),
    MENGENEINHEIT   VARCHAR(25),
    KALORIEN        INTEGER,
    BESTAND         INTEGER,
    NETTOPREIS      DECIMAL(10,2),
    FETT            DECIMAL(10,2),
    KOHLENHYDRATE   DECIMAL(10,2),
    PROTEIN         DECIMAL(10,2),
    PRIMARY KEY (ZID)
);

CREATE TABLE ALLERGENE (
    AID             VARCHAR(1),
    BESCHREIBUNG    VARCHAR(500),
    ALLERGEN     	VARCHAR(25),
    PRIMARY KEY (AID)
);

CREATE TABLE ENKATEGORIE (
    EID             INTEGER NOT NULL,
    BESCHREIBUNG    VARCHAR(500),
    EAKATEGORIENAME		VARCHAR(25),
    PRIMARY KEY (EID)
);

CREATE TABLE LIEFERANT (
    LIEFERANTENNR   INTEGER AUTO_INCREMENT NOT NULL,
    STRASSE         VARCHAR(50),
    HAUSNR          VARCHAR(6),
    LIEFERANT       VARCHAR(25),
    PLZ             VARCHAR(5),
    EMAIL           VARCHAR(50),
    TELEFON         VARCHAR(25),
    PRIMARY KEY (LIEFERANTENNR)
);

CREATE TABLE ORT (
    PLZ             VARCHAR(5),
    STADT           VARCHAR(50),
    PRIMARY KEY (PLZ)
);

CREATE TABLE REZEPTE (
    RID             INTEGER AUTO_INCREMENT NOT NULL,
    REZEPTE         VARCHAR(25),
    BESCHREIBUNG    VARCHAR(500),
    PRIMARY KEY (RID)
);

CREATE TABLE BESTELLUNGZUTATEN (
    BESTELLNR       INTEGER,
    ZID             INTEGER,
    MENGE           INTEGER
);

CREATE TABLE ZUTATENALLERGENE (
    AID             VARCHAR(1),
    ZID             INTEGER
);

CREATE TABLE ZUTATENEKG (
    EID             INTEGER,
    ZID             INTEGER
);

CREATE TABLE REZEPTZUTATEN (
    RID             INTEGER,
    ZID             INTEGER,
    MENGE           INTEGER
);

CREATE TABLE LIEFERANTZUTATEN ( 
    LIEFERANTENNR       INTEGER,
    ZID                 INTEGER
);

/******************************************************************************/
/***                              Foreign Keys                              ***/
/******************************************************************************/

ALTER TABLE KUNDE ADD FOREIGN KEY (PLZ) REFERENCES ORT (PLZ);
ALTER TABLE LIEFERANT ADD FOREIGN KEY (PLZ) REFERENCES ORT (PLZ);
ALTER TABLE BESTELLUNGZUTATEN ADD FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG (BESTELLNR); 
ALTER TABLE BESTELLUNG ADD FOREIGN KEY (KUNDENNR) REFERENCES KUNDE (KUNDENNR);
ALTER TABLE BESTELLUNGZUTATEN ADD FOREIGN KEY (ZID) REFERENCES ZUTATEN(ZID);
ALTER TABLE ZUTATENALLERGENE ADD FOREIGN KEY (AID) REFERENCES ALLERGENE(AID);
ALTER TABLE ZUTATENALLERGENE ADD FOREIGN KEY (ZID) REFERENCES ZUTATEN(ZID);
ALTER TABLE ZUTATENEKG ADD FOREIGN KEY (EID) REFERENCES ENKATEGORIE(EID);
ALTER TABLE ZUTATENEKG ADD FOREIGN KEY (ZID) REFERENCES ZUTATEN(ZID);
ALTER TABLE REZEPTZUTATEN ADD FOREIGN KEY (RID) REFERENCES REZEPTE (RID);
ALTER TABLE REZEPTZUTATEN ADD FOREIGN KEY (ZID) REFERENCES ZUTATEN(ZID);
ALTER TABLE LIEFERANTZUTATEN ADD FOREIGN KEY (LIEFERANTENNR) REFERENCES LIEFERANT (LIEFERANTENNR);
ALTER TABLE LIEFERANTZUTATEN ADD FOREIGN KEY (ZID) REFERENCES ZUTATEN(ZID);
